### ISSUE TITLE
grass_json not defined

### ISSUE THREAD

**Issue by DerangedWifi** [icrdr/Resource-Pack-Converter#7]
Just like title. Console run its normal course then stops here.

**Comment by DerangedWifi** [comment]
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1699, in __call__
  File "convert_tool.py", line 37, in selectPack
  File "main.py", line 691, in main
  File "main.py", line 699, in conversion
  File "main.py", line 263, in changeModel
NameError: name 'grass_json' is not defined
